---
- name: Configure Git (optional)
  ansible.builtin.shell: |
    git config --global user.name "{{ ludus_git_user_name }}"
    git config --global user.email "{{ ludus_git_user_email }}"
  become_user: "kali"
  when: ludus_configure_git and ludus_git_user_name and ludus_git_user_email
  changed_when: false

- name: Create .hushlogin file
  ansible.builtin.file:
    path: "/home/kali/.hushlogin"
    state: touch
    owner: "kali"
    group: "kali"
    mode: '0644'
